-- Applied to Neon project networking-tracker, branch: production
-- Run via the Neon console SQL Editor.

CREATE TABLE contacts (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    text        NOT NULL DEFAULT (auth.user_id()),
  name       text        NOT NULL CHECK (length(btrim(name)) > 0),
  company    text,
  role       text,
  where_met  text,
  notes      text,
  priority   text        NOT NULL CHECK (priority IN ('high', 'medium', 'low')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

CREATE POLICY contacts_select ON contacts
  FOR SELECT TO authenticated
  USING (auth.user_id() = user_id);

CREATE POLICY contacts_insert ON contacts
  FOR INSERT TO authenticated
  WITH CHECK (auth.user_id() = user_id);

CREATE POLICY contacts_update ON contacts
  FOR UPDATE TO authenticated
  USING (auth.user_id() = user_id)
  WITH CHECK (auth.user_id() = user_id);

CREATE POLICY contacts_delete ON contacts
  FOR DELETE TO authenticated
  USING (auth.user_id() = user_id);
